/*
 * This source file was generated by the Gradle 'init' task
 */
package coffeehouse;

import coffeehouse.contract.order.Order;
import coffeehouse.contract.order.OrderServiceGrpc;
import io.grpc.ManagedChannelBuilder;

public class App {

    public static void main(String[] args) {
         var channel = ManagedChannelBuilder
                 .forAddress("localhost", 50051)
                 .usePlaintext()
                 .build();

         var stub = OrderServiceGrpc.newBlockingStub(channel);

         var request = Order.PlaceOrderRequest.newBuilder()
                 .setCustomerId("java-user-1234")
                 .addOrderLines(Order.OrderLine.newBuilder().setProductCode("ESPRESSO").setQuantity(2).build())
                 .addOrderLines(Order.OrderLine.newBuilder().setProductCode("LATTE").setQuantity(1).build())
                 .build();
         var response = stub.placeOrder(request);

        try {
            System.out.println("✅ Java 클라이언트 - 주문 완료, 주문 ID: " + response.getOrderId());
        } catch (Exception error) {
            System.out.println("✅ Java 클라이언트 - 주문 오류: " + error.getMessage());
        }

        channel.shutdown();
    }

}
