/*
 * This source file was generated by the Gradle 'init' task
 */
package coffeehouse

import coffeehouse.contract.order.Order.PlaceOrderRequest
import coffeehouse.contract.order.Order.PlaceOrderResponse
import coffeehouse.contract.order.OrderServiceGrpcKt
import io.grpc.ServerBuilder
import kotlinx.coroutines.runBlocking
import java.util.*

class OrderServiceImpl : OrderServiceGrpcKt.OrderServiceCoroutineImplBase() {
    override suspend fun placeOrder(request: PlaceOrderRequest): PlaceOrderResponse {
        val orderId = UUID.randomUUID().toString()
        println("📦 주문 생성: 고객ID=${request.customerId}, 주문ID=$orderId, 주문 목록=${request.orderLinesList}")
        return PlaceOrderResponse.newBuilder().setOrderId(orderId).build()
    }
}

fun main() = runBlocking {
    val server = ServerBuilder
        .forPort(50051)
        .addService(OrderServiceImpl())
        .build()
        .start()

    println("✅ gRPC 커피 주문 서버 실행 중... (포트 50051)")
    server.awaitTermination()
}
